spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: minhdb
      
mongodb:
  primary:
    host: localhost
    port: 27017
    database: minhdb
collection_name: myCollection	














